#include "data_cfg.h"


data_bundle_cfg cfg_atm_output_data_bundle = {NAME_ATM_OUTPUT_FIELDS,
                                                              19, 
                                                              0,
                                                              {{"Sa_z", 2},
                                                                {"Sa_u", 2},
                                                                {"Sa_v", 2},
                                                                {"Sa_tbot", 2},
                                                                {"Sa_ptem", 2},
                                                                {"Sa_shum", 2},
                                                                {"Sa_dens", 2},
                                                                {"Sa_pbot", 2},
                                                                {"Sa_pslv", 2},
                                                                {"Faxa_lwdn", 2},
                                                                {"Faxa_rainc", 2},
                                                                {"Faxa_rainl", 2},
                                                                {"Faxa_snowc", 2},
                                                                {"Faxa_snowl", 2},
                                                                {"Faxa_swndr", 2},
                                                                {"Faxa_swvdr", 2},
                                                                {"Faxa_swndf", 2},
                                                                {"Faxa_swvdf", 2},
                                                                {"Faxa_swnet", 2}}};

data_bundle_cfg cfg_atm_input_data_bundle = {NAME_ATM_INPUT_FIELDS,
                                                              17,
                                                              0,
                                                              {{"Sx_tref", 2},
                                                              {"Sx_qref", 2},
                                                              {"Sx_avsdr", 2},
                                                              {"Sx_anidr", 2},
                                                              {"Sx_avsdf", 2},
                                                              {"Sx_anidf", 2},
                                                              {"Sx_t", 2},
                                                              {"So_t", 2},
                                                              {"Sx_snowh", 2},
                                                              {"Sx_ifrac", 2},
                                                              {"Sx_ofrac", 2},
                                                              {"Faxx_taux", 2},
                                                              {"Faxx_tauy", 2},
                                                              {"Faxx_lat", 2},
                                                              {"Faxx_sen", 2},
                                                              {"Faxx_lwup", 2},
                                                              {"Faxx_evap", 2}}};

data_bundle_cfg cfg_ocn_output_data_bundle = {NAME_OCN_OUTPUT_FIELDS,
                                                              7,
                                                              0,
                                                              {{"So_t", 2},
                                                              {"So_u", 2},
                                                              {"So_v", 2},
                                                              {"So_s", 2},
                                                              {"So_dhdx", 2},
                                                              {"So_dhdy", 2},
                                                              {"Fioo_q", 2}}};

data_bundle_cfg cfg_ocn_input_data_bundle = {NAME_OCN_INPUT_FIELDS,
                                                              18,
                                                              0,
                                                              {{"Si_ifrac", 2},
                                                              {"Sa_pslv", 2},
                                                              {"Faoc_duu10n", 2},
                                                              {"Foxx_taux", 2},
                                                              {"Foxx_tauy", 2},
                                                              {"Foxx_swnet", 2},
                                                              {"Foxx_lat", 2},
                                                              {"Foxx_sen", 2},
                                                              {"Foxx_lwup", 2},
                                                              {"Foxx_lwdn", 2},
                                                              {"Foxx_melth", 2},
                                                              {"Foxx_salt", 2},
                                                              {"Foxx_prec", 2},
                                                              {"Foxx_snow", 2},
                                                              {"Foxx_rain", 2},
                                                              {"Foxx_evap", 2},
                                                              {"Foxx_meltw", 2},
                                                              {"Forr_roff", 2}}};

data_bundle_cfg cfg_lnd_output_data_bundle = {NAME_LND_OUTPUT_FIELDS,
                                                             15,
                                                             0,
                                                             {{"Sl_t", 2},
                                                             {"Sl_tref", 2},
                                                             {"Sl_qref", 2},
                                                             {"Sl_avsdr", 2},
                                                             {"Sl_anidr", 2},
                                                             {"Sl_avsdf", 2},
                                                             {"Sl_anidf", 2},
                                                             {"Sl_snowh", 2},
                                                             {"Fall_taux", 2},
                                                             {"Fall_tauy", 2},
                                                             {"Fall_lat", 2},
                                                             {"Fall_sen", 2},
                                                             {"Fall_lwup", 2},
                                                             {"Fall_evap", 2},
                                                             {"Fall_swnet", 2}}};

data_bundle_cfg cfg_roff_output_data_bundle = {NAME_ROFF_OUTPUT_FIELDS,
                                                              1,
                                                              0,
                                                              {{"Forr_roff", 2}}};

data_bundle_cfg cfg_lnd_input_data_bundle = {NAME_LND_INPUT_FIELDS,
                                                             18,
                                                             0,
                                                             {{"Sa_z", 2},
                                                             {"Sa_u", 2},
                                                             {"Sa_v", 2},
                                                             {"Sa_tbot", 2},
                                                             {"Sa_ptem", 2},
                                                             {"Sa_shum", 2},
                                                             {"Sa_dens", 2},
                                                             {"Sa_pbot", 2},
                                                             {"Sa_pslv", 2},
                                                             {"Faxa_lwdn", 2},
                                                             {"Faxa_rainc", 2},
                                                             {"Faxa_rainl", 2},
                                                             {"Faxa_snowc", 2},
                                                             {"Faxa_snowl", 2},
                                                             {"Faxa_swndr", 2},
                                                             {"Faxa_swvdr", 2},
                                                             {"Faxa_swndf", 2},
                                                             {"Faxa_swvdf", 2}}};

data_bundle_cfg cfg_sice_output_data_bundle = {NAME_SICE_OUTPUT_FIELDS,
                                                        22,
                                                        0,
                                                        {{"Si_t", 2},
                                                        {"Si_tref", 2},
                                                        {"Si_qref", 2},
                                                        {"Si_ifrac", 2},
                                                        {"Si_avsdr", 2},
                                                        {"Si_anidr", 2},
                                                        {"Si_avsdf", 2},
                                                        {"Si_anidf", 2},
                                                        {"Index", 2},
                                                        {"Faii_taux", 2},
                                                        {"Faii_tauy", 2},
                                                        {"Faii_lat", 2},
                                                        {"Faii_sen", 2},
                                                        {"Faii_lwup", 2},
                                                        {"Faii_evap", 2},
                                                        {"Faii_swnet", 2},
                                                        {"Fioi_swpen", 2},
                                                        {"Fioi_melth", 2},
                                                        {"Fioi_meltw", 2},
                                                        {"Fioi_salt", 2},
                                                        {"Fioi_taux", 2},
                                                        {"Fioi_tauy", 2}}};

data_bundle_cfg cfg_sice_input_data_bundle = {NAME_SICE_INPUT_FIELDS,
                                                        21,
                                                        0,
                                                        {{"So_t", 2},
                                                        {"So_s", 2},
                                                        {"So_u", 2},
                                                        {"So_v", 2},
                                                        {"Sa_z", 2},
                                                        {"Sa_u", 2},
                                                        {"Sa_v", 2},
                                                        {"Sa_ptem", 2},
                                                        {"Sa_tbot", 2},
                                                        {"Sa_shum", 2},
                                                        {"Sa_dens", 2},
                                                        {"So_dhdx", 2},
                                                        {"So_dhdy", 2},
                                                        {"Fioo_q", 2},
                                                        {"Faxa_swndr", 2},
                                                        {"Faxa_swvdr", 2},
                                                        {"Faxa_swndf", 2},
                                                        {"Faxa_swvdf", 2},
                                                        {"Faxa_lwdn", 2},
                                                        {"Faxc_rain", 2},
                                                        {"Faxc_snow", 2}}};

data_bundle_cfg cfg_atm_ocn_data_bundle = {NAME_ATM_OCN_FIELDS,
                                                         10,
                                                         0,
                                                         {{"Faoc_sen", 2},
                                                         {"Faoc_lat", 2},
                                                         {"Faoc_lwup", 2},
                                                         {"Faoc_evap", 2},
                                                         {"Faoc_taux", 2},
                                                         {"Faoc_tauy", 2},
                                                         {"Faoc_tref", 2},
                                                         {"Faoc_qref", 2},
                                                         {"Faoc_duu10n", 2},
                                                         {"Faoc_swnet", 2},
                                                         {"So_avsdr", 2},
                                                         {"So_anidr", 2},
                                                         {"So_avsdf", 2},
                                                         {"So_anidf", 2},
                                                         {"Faxc_rain", 2},
                                                         {"Faxc_snow", 2}}};



